STATUS_ALIVE = 'ALIVE'
STATUS_DEAD = 'DEAD'

SQUARE_EMPTY = 0
SQUARE_SHIP_ALIVE = 1
SQUARE_SHIP_DEAD = 2
SQUARE_FIRED = 3
SQUARE_TMP = 4

FOUR_YARD_SHIP = 4
THREE_YARD_SHIP = 3
TWO_YARD_SHIP = 2
ONE_YARD_SHIP = 1

SHIP_NAMES = [
    FOUR_YARD_SHIP,
    THREE_YARD_SHIP,
    THREE_YARD_SHIP,
    TWO_YARD_SHIP,
    TWO_YARD_SHIP,
    TWO_YARD_SHIP,
    ONE_YARD_SHIP,
    ONE_YARD_SHIP,
    ONE_YARD_SHIP,
    ONE_YARD_SHIP
]

SHIP_NAME_LENGTH = {
    FOUR_YARD_SHIP: 4,
    THREE_YARD_SHIP: 3,
    TWO_YARD_SHIP: 2,
    ONE_YARD_SHIP: 1
}
